initial_pose:
  frame_id: map
  x: 0.7100967168807983
  y: 0.6245508193969727
  # yaw는 네 quaternion이 거의 -90deg 근처라서 (-1.5708) 정도일 가능성이 큼
  # 정확히는 atan2(2*w*z, 1-2*z^2)로 계산되는데, 대략 -1.571로 두면 됨.
  yaw: -1.5708
