# ============================
# Nav2 Params (Isaac Sim 5.0 / TIAGo) - FINAL (base_footprint)
# ============================

amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"
    tf_broadcast: true
    scan_topic: "/scan_front_raw"
    min_particles: 500
    max_particles: 2000
    use_map_topic: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/ros/tiago-delivery/ros2_ws/src/navigation/tiago_nav2/maps/lobby_map.yaml"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "base_footprint"
    odom_topic: "/odom"
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 8.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.15
      lookahead_dist: 0.3
      transform_tolerance: 0.5
      use_rotate_to_heading: true
      rotate_to_heading_angular_vel: 0.6
      rotate_to_heading_min_angle: 0.4
      allow_reversing: false
      use_velocity_scaled_lookahead_dist: true
      min_lookahead_dist: 0.2
      max_lookahead_dist: 0.6
      lookahead_time: 1.0
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0
      min_approach_linear_velocity: 0.05
      use_curvature_regulated_linear_velocity_scaling: true
      curvature_scaling_dist: 0.9
      curvature_scaling_gain: 1.0

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      allow_unknown: true

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: "map"
      robot_base_frame: "base_footprint"
      update_frequency: 2.0
      publish_frequency: 1.0
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      robot_radius: 0.3
      transform_tolerance: 0.5
      always_send_full_costmap: true

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "/scan_front_raw"
          data_type: "LaserScan"
          marking: true
          clearing: true
          obstacle_max_range: 6.0
          raytrace_max_range: 8.0
          qos:
            reliability: "best_effort"
            durability: "volatile"
            history: "keep_last"
            depth: 5

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 2.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: "odom"
      robot_base_frame: "base_footprint"
      rolling_window: true

      resolution: 0.05

      update_frequency: 10.0
      publish_frequency: 5.0

      transform_tolerance: 0.5
      always_send_full_costmap: true
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "/scan_front_raw"
          data_type: "LaserScan"
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          obstacle_max_range: 6.0
          raytrace_max_range: 8.0
          qos:
            reliability: "best_effort"
            durability: "volatile"
            history: "keep_last"
            depth: 5

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.1
        cost_scaling_factor: 3.0

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ["map_server", "amcl"]

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ["planner_server", "controller_server", "bt_navigator", "local_costmap", "global_costmap"]
